latest-jobs-configurations:
  get:
    tags:
      - configuration
    summary: Get the latest jobs configurations
    operationId: getLatestJobsConfigurations
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: A list of all the latest known jobs configurations or empty list if no jobs configurations are present.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '500':
        $ref: './responses.yaml#/500'
  post:
    tags:
      - configuration
    summary: Update the latest jobs configurations
    operationId: updateLatestJobsConfigurations
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: The latest jobs configurations have been successfully updated.
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '404':
        description: Latest configuration not found.
      '500':
        $ref: './responses.yaml#/500'
configurations:
  get:
    tags:
      - configuration
    summary: Get all application configurations
    operationId: getAllConfigurations
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: A list of all known configurations or empty list if no configurations are present.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '500':
        $ref: './responses.yaml#/500'
