latest-jobs-configurations:
  get:
    tags:
      - configuration
    summary: Get the latest jobs configurations
    operationId: getLatestJobsConfigurations
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: A list of all the latest known jobs configurations or empty list if no jobs configurations are present.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '500':
        $ref: './responses.yaml#/500'
  post:
    tags:
      - configuration
    summary: Update the latest jobs configurations
    operationId: updateLatestJobsConfigurations
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: The latest jobs configurations have been successfully updated.
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '404':
        description: Latest configuration not found.
      '500':
        $ref: './responses.yaml#/500'
latest-jobs-configuration-by-audit-type:
  parameters:
    - $ref: './parameters.yaml#/auditType'
  get:
    tags:
      - configuration
    summary: Get the latest jobs configurations by audit type
    description: |
      This endpoint is useful for retrieving the latest jobs configurations by audit type.
    operationId: getLatestJobsConfigurationsByAuditType
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: A list of all the latest known jobs configurations for specific type or empty list if no jobs configurations for specific type returned.
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/Configuration'
      '400':
        $ref: './responses.yaml#/400-no-audit-type'
      '401':
        $ref: './responses.yaml#/401'
      '404':
        $ref: './responses.yaml#/404'
      '500':
        $ref: './responses.yaml#/500'
  delete:
    tags:
      - configuration
    summary: Delete the latest jobs configurations by audit type
    description: |
      This endpoint is useful for deleting the latest jobs configurations by a specific audit type.
    operationId: deleteLatestJobsConfigurationsByAuditType
    security:
      - admin_key: [ ]
    responses:
      '204':
        description: Latest jobs configurations for specific audit type deleted successfully
      '400':
        $ref: './responses.yaml#/400-no-audit-type'
      '401':
        $ref: './responses.yaml#/401'
      '404':
        $ref: './responses.yaml#/404'
      '500':
        $ref: './responses.yaml#/500'
# should we require an api key for this endpoint?
#    security:
#      - api_key: [ ]
configurations:
  get:
    tags:
      - configuration
    summary: Get all application configurations
    operationId: getAllConfigurations
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: A list of all known configurations or empty list if no configurations are present.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '500':
        $ref: './responses.yaml#/500'
